In [3]:
#naive
import numpy as np
import math as mp
import matplotlib.pyplot as plt
import pandas as pd
import statistics as st
import seaborn as sns
from sklearn.metrics import accuracy_score

In [4]:
df=pd.read_csv("PlayTennis.csv")
df

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [5]:
class normal_naive:
    
    def __init__(self):
        pass
    
    def probability(self,event,sample_space):
        p=np.count_nonzero(event==sample_space)/len(sample_space)
        return p 
    
    def fit(self,x_train,y_train):
        self.x_train=x_train
        self.y_train=y_train
     
    def conditional(self,event_sample,event,condition,condition_sample):
        num=np.count_nonzero((event_sample==event)&(condition_sample==condition))
        deno=np.count_nonzero(condition_sample==condition)
        return num/deno  if deno>0 else 0
           
    def predict(self,x_test):
        
        self.x_test=x_test       
        
        x_test=self.x_test.to_numpy()     # same can be done without changing to dataframe as well
        y_train=self.y_train.to_numpy()
        x_train=self.x_train.to_numpy()
        
        target = np.unique(y_train)
        result=[]
        
        for feat in x_test:  # it is a collection of ["sunny","hot","normal","flase"] like list 
            prob=[]
            for i in target:  # yes/no in our case
                prior_target = self.probability(i,y_train)
        
                likelihood = 1
                prior_evidence = 1
                
                for j in range(len(feat)):
                        likelihood = self.conditional(x_train[:,j],feat[j],i,y_train) * likelihood
                        prior_evidence=self.probability(feat[j],x_train[:,j]) * prior_evidence
                        
                bayes = likelihood * prior_target / prior_target
                
                prob.append(bayes)
                
            prediction_target=target[prob.index(max(prob))]    
            result.append(prediction_target)

            
        return result

In [13]:
x=df.drop(["play"],axis=1)
y=df["play"]
df

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [8]:
nave=normal_naive()
nave.fit(X_train,y_train)
pred=nave.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.8

In [10]:
pred

['yes', 'yes', 'no', 'yes', 'yes']

In [11]:
y_test

9     yes
11    yes
0      no
12    yes
5      no
Name: play, dtype: object

In [12]:
y_test==pred

9      True
11     True
0      True
12     True
5     False
Name: play, dtype: bool